# Generated by Django 5.2.17 on 2026-09-02 21:45

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0010_enable_mobility_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobilityListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("offer", "Ich biete"), ("request", "Ich suche")],
                        max_length=12,
                    ),
                ),
                (
                    "transport",
                    models.CharField(
                        choices=[
                            ("car", "Auto"),
                            ("bicycle", "Fahrrad"),
                            ("walk", "Zu Fuß"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("to_school", "Hinweg zur Schule"),
                            ("from_school", "Rückweg von der Schule"),
                            ("both", "Hin- und Rückweg"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("approximate_area", models.CharField(blank=True, max_length=120)),
                ("weekdays", models.JSONField(default=list)),
                ("time_from", models.TimeField()),
                ("time_until", models.TimeField()),
                (
                    "seats",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(12)],
                    ),
                ),
                (
                    "max_detour_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                ("valid_until", models.DateField()),
                ("notes", models.CharField(blank=True, max_length=600)),
                ("safety_confirmed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("paused", "Pausiert"),
                            ("matched", "Vermittelt"),
                            ("expired", "Abgelaufen"),
                            ("withdrawn", "Zurückgezogen"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.schoolclass",
                    ),
                ),
            ],
            options={
                "ordering": ["time_from", "title"],
            },
        ),
        migrations.CreateModel(
            name="MeetingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=240)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("meeting_time", models.TimeField(blank=True, null=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_points",
                        to="mobility.mobilitylisting",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="MobilityListingView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_on", models.DateField()),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_events",
                        to="mobility.mobilitylisting",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MobilityReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("interested", "Interessiert"),
                            ("seat_offered", "Platz angeboten"),
                            ("question", "Rückfrage"),
                        ],
                        max_length=16,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=400)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Offen"),
                            ("accepted", "Angenommen"),
                            ("declined", "Abgelehnt"),
                            ("withdrawn", "Zurückgezogen"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="mobility.mobilitylisting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MobilityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="mobility.mobilitylisting",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PickupDisclosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_address", models.TextField()),
                (
                    "purpose",
                    models.CharField(default="Vereinbarte Abholung", max_length=160),
                ),
                ("valid_until", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_disclosures",
                        to="mobility.mobilitylisting",
                    ),
                ),
                (
                    "reaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mobility.mobilityreaction",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_pickups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shared_pickups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="mobilitylisting",
            index=models.Index(
                fields=["school_class", "status", "valid_until"],
                name="mobility_mo_school__a98862_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="mobilitylistingview",
            constraint=models.UniqueConstraint(
                fields=("listing", "viewer", "viewed_on"),
                name="unique_daily_mobility_view",
            ),
        ),
        migrations.AddConstraint(
            model_name="mobilityreaction",
            constraint=models.UniqueConstraint(
                fields=("listing", "user"), name="unique_mobility_reaction"
            ),
        ),
        migrations.AddConstraint(
            model_name="mobilityreport",
            constraint=models.UniqueConstraint(
                fields=("listing", "reporter"), name="unique_mobility_report"
            ),
        ),
    ]
