# Generated by Django 5.2.17 on 2026-09-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributioncategory",
            name="source_imported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contributioncategory",
            name="source_provider",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="contributioncategory",
            name="source_reference",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="contributioncategory",
            name="source_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name="contributioncategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_reference", ""), _negated=True),
                fields=("event", "source_provider", "source_reference"),
                name="unique_event_external_contribution_source",
            ),
        ),
    ]
