# Generated by Django 5.2.17 on 2026-09-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_polls"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="meeting_url",
            field=models.URLField(blank=True),
        ),
    ]
