# Generated by Django 5.2.17 on 2026-09-09 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_normalize_person_phones"),
        ("portal_adapters", "0003_centralize_adapters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="portaladapter",
            name="provider",
            field=models.CharField(
                choices=[
                    ("webuntis", "WebUntis"),
                    ("itslearning", "itslearning"),
                    ("mensamax", "MensaMax"),
                    ("dsbmobile", "DSBmobile"),
                    ("mundo", "MUNDO Schule"),
                    ("wirlernenonline", "WirLernenOnline"),
                    ("schulmanager", "Schulmanager Online"),
                    ("wobila-bbb", "BBB Wobila"),
                    ("wobila-mail", "Mail Wobila"),
                    ("custom", "Eigenes Portal"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="SchoolmanagerConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username_encrypted", models.BinaryField()),
                ("password_encrypted", models.BinaryField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_tested", "Noch nicht geprüft"),
                            ("ok", "Verbindung eingerichtet"),
                            ("invalid", "Zugangsdaten ungültig"),
                            ("error", "Verbindung fehlerhaft"),
                        ],
                        default="not_tested",
                        max_length=24,
                    ),
                ),
                ("status_detail", models.CharField(blank=True, max_length=160)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schoolmanager_connections",
                        to="core.person",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schoolmanager_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "student"),
                        name="unique_schoolmanager_user_student",
                    )
                ],
            },
        ),
    ]
