# Generated by Django 5.2.17 on 2026-09-23 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal_adapters", "0006_normalize_webuntis_absences"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalAdapterDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=32, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("hint", models.CharField(blank=True, max_length=300)),
                ("default_url", models.URLField(blank=True)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("import", "Datenimport"),
                            ("external", "Externes Portal"),
                            ("custom", "Individuelle Schnittstelle"),
                        ],
                        default="import",
                        max_length=16,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_technically_reviewed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("label",),
            },
        ),
        migrations.AddField(
            model_name="portaladaptermodule",
            name="access_model",
            field=models.CharField(
                choices=[
                    ("none", "Ohne persönlichen Zugang"),
                    ("child", "Zugang je Kind"),
                    ("family", "Zugang je Familie"),
                    ("external", "Nur extern öffnen"),
                ],
                default="none",
                help_text="Fachliches Zugangsmodell für Familien und Kinder.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="portaladapter",
            name="definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="school_integrations",
                to="portal_adapters.portaladapterdefinition",
            ),
        ),
        migrations.CreateModel(
            name="PortalAdapterDefinitionModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "access_model",
                    models.CharField(
                        choices=[
                            ("none", "Ohne persönlichen Zugang"),
                            ("child", "Zugang je Kind"),
                            ("family", "Zugang je Familie"),
                            ("external", "Nur extern öffnen"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="portal_adapters.portaladapterdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ("label",),
            },
        ),
        migrations.AddField(
            model_name="portaladaptermodule",
            name="definition_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="school_modules",
                to="portal_adapters.portaladapterdefinitionmodule",
            ),
        ),
        migrations.AddConstraint(
            model_name="portaladapterdefinitionmodule",
            constraint=models.UniqueConstraint(
                fields=("definition", "key"), name="unique_adapter_definition_module"
            ),
        ),
    ]
