# Generated by Django 5.2.17 on 2026-09-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_room_appearance_and_optional_retention"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="parent_representative_chat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                fields=["school_class"],
                condition=models.Q(parent_representative_chat=True),
                name="unique_parent_representative_chat_per_class",
            ),
        ),
    ]
