# Generated by Django 5.2.17 on 2026-08-25 16:16

import django.db.models.deletion
import django.utils.timezone
import klasse5e.media.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_alter_useraccount_managers"),
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("published", "Veröffentlicht"),
                            ("archived", "Archiviert"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("upload_allowed", models.BooleanField(default=False)),
                ("download_allowed", models.BooleanField(default=False)),
                ("moderation_required", models.BooleanField(default=True)),
                ("retention_until", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.event",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.schoolclass",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.schoolyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("clarification", "Klärung"),
                            ("published", "Veröffentlicht"),
                            ("rejected", "Abgelehnt"),
                            ("hidden", "Ausgeblendet"),
                            ("withdrawn", "Zurückgezogen"),
                            ("deleted", "Gelöscht"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("original_name", models.CharField(max_length=180)),
                (
                    "display_file",
                    models.FileField(upload_to=klasse5e.media.models.photo_path),
                ),
                (
                    "thumbnail_file",
                    models.FileField(upload_to=klasse5e.media.models.photo_path),
                ),
                (
                    "download_file",
                    models.FileField(blank=True, upload_to=klasse5e.media.models.photo_path),
                ),
                ("content_type", models.CharField(max_length=20)),
                ("size", models.PositiveBigIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                ("reason_code", models.CharField(blank=True, max_length=40)),
                ("retention_until", models.DateTimeField()),
                ("description", models.CharField(blank=True, max_length=500)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("download_allowed", models.BooleanField(default=False)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="media.gallery",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhotoModerationDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decision", models.CharField(max_length=24)),
                ("reason", models.CharField(blank=True, max_length=40)),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "consent_policy_version",
                    models.CharField(default="photo-policy-v1", max_length=32),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="media.photo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhotoSubjectDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("none", "Keine erkennbare Person"),
                            ("adults", "Nur Erwachsene"),
                            ("known", "Bekannte Person"),
                            ("unclear", "Weitere oder unklare Person"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Vorgeschlagen"),
                            ("confirmed", "Bestätigt"),
                            ("rejected", "Abgelehnt"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_photo_declarations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "declared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photo_declarations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.person",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_declarations",
                        to="media.photo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhotoReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("missing_consent", "Fehlende Zustimmung"),
                            ("wrong_person", "Falsche Personenangabe"),
                            ("inappropriate", "Ungeeigneter Inhalt"),
                            ("privacy", "Datenschutz"),
                            ("accidental", "Versehentlicher Upload"),
                            ("other", "Sonstiger Hinweis"),
                        ],
                        max_length=24,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("status", models.CharField(default="open", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_photo_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="media.photo",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("photo", "reporter", "reason"),
                        name="unique_photo_report",
                    )
                ],
            },
        ),
    ]
