# Generated by Django 5.2.17 on 2026-08-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="retention_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
