# Generated by Django 5.2.17 on 2026-08-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_alter_gallery_retention_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="biometric_analysis_allowed",
            field=models.BooleanField(
                default=False,
                help_text="Separate ausdrückliche Freigabe für die lokale technische Analyse",
            ),
        ),
    ]
