# Generated by Django 5.2.17 on 2026-09-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0004_photo_ai_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="event_category",
            field=models.CharField(
                choices=[
                    ("class_trip", "Klassenfahrt"),
                    ("excursion", "Schulausflug"),
                    ("celebration", "Feier"),
                    ("school_event", "Schulveranstaltung"),
                    ("lesson", "Unterrichtsprojekt"),
                    ("other", "Sonstiges Ereignis"),
                ],
                default="other",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="correction_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="finalized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="resubmission_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="photo",
            name="review_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
