# Generated by Django 5.2.17 on 2026-08-25 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import klasse5e.content.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_alter_useraccount_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("category", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Entwurf"), ("published", "Veröffentlicht")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("pinned", models.BooleanField(default=False)),
                ("important", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("comments_closed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.schoolclass",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.schoolyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=4000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("visible", "Sichtbar"),
                            ("withdrawn", "Zurückgezogen"),
                            ("hidden", "Moderiert"),
                        ],
                        default="visible",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="content.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProtectedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(max_length=80)),
                ("document_date", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("version", models.CharField(max_length=32)),
                (
                    "original",
                    models.FileField(
                        upload_to=klasse5e.content.models.protected_path,
                        validators=[klasse5e.content.models.validate_pdf],
                    ),
                ),
                (
                    "fillable",
                    models.FileField(
                        blank=True,
                        upload_to=klasse5e.content.models.protected_path,
                        validators=[klasse5e.content.models.validate_pdf],
                    ),
                ),
                ("is_updated", models.BooleanField(default=False)),
                ("acknowledgement_required", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Entwurf"), ("published", "Veröffentlicht")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.schoolclass",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.schoolyear",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="attachments",
            field=models.ManyToManyField(blank=True, to="content.protecteddocument"),
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subjects", models.CharField(max_length=300)),
                ("class_function", models.CharField(max_length=120)),
                ("school_email", models.EmailField(blank=True, max_length=254)),
                ("office_hours", models.CharField(blank=True, max_length=160)),
                ("introduction", models.TextField(blank=True)),
                (
                    "email_visibility",
                    models.CharField(
                        choices=[
                            ("self", "Nur eigene Person"),
                            ("admins", "Administratoren"),
                            ("teachers", "Klassenlehrer und Administratoren"),
                            ("members", "Aktive Klassenmitglieder"),
                            ("hidden", "Nicht sichtbar"),
                        ],
                        default="hidden",
                        max_length=16,
                    ),
                ),
                (
                    "office_hours_visibility",
                    models.CharField(
                        choices=[
                            ("self", "Nur eigene Person"),
                            ("admins", "Administratoren"),
                            ("teachers", "Klassenlehrer und Administratoren"),
                            ("members", "Aktive Klassenmitglieder"),
                            ("hidden", "Nicht sichtbar"),
                        ],
                        default="hidden",
                        max_length=16,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.person"
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.schoolclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.comment",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("comment", "reporter"), name="unique_comment_report"
                    )
                ],
            },
        ),
    ]
