# Generated by Django 5.2.17 on 2026-08-24 21:46

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=160)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "Allgemein"),
                            ("photo", "Foto"),
                            ("biometric", "Biometrie"),
                        ],
                        max_length=16,
                    ),
                ),
                ("purpose", models.TextField()),
                ("recipients", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="SchoolYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=32, unique=True)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("action", models.CharField(max_length=80)),
                ("target_type", models.CharField(max_length=80)),
                ("target_id", models.CharField(blank=True, max_length=128)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentTextVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                (
                    "text",
                    models.TextField(help_text="Fachlicher Entwurf bis zur rechtlichen Freigabe"),
                ),
                ("effective_from", models.DateTimeField()),
                (
                    "consent_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.consenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("other_contact", models.CharField(blank=True, max_length=200)),
                (
                    "email_visibility",
                    models.CharField(
                        choices=[
                            ("self", "Nur eigene Person"),
                            ("admins", "Administratoren"),
                            ("teachers", "Klassenlehrer und Administratoren"),
                            ("members", "Aktive Klassenmitglieder"),
                            ("hidden", "Nicht sichtbar"),
                        ],
                        default="hidden",
                        max_length=16,
                    ),
                ),
                (
                    "phone_visibility",
                    models.CharField(
                        choices=[
                            ("self", "Nur eigene Person"),
                            ("admins", "Administratoren"),
                            ("teachers", "Klassenlehrer und Administratoren"),
                            ("members", "Aktive Klassenmitglieder"),
                            ("hidden", "Nicht sichtbar"),
                        ],
                        default="hidden",
                        max_length=16,
                    ),
                ),
                (
                    "relationship_visibility",
                    models.CharField(
                        choices=[
                            ("self", "Nur eigene Person"),
                            ("admins", "Administratoren"),
                            ("teachers", "Klassenlehrer und Administratoren"),
                            ("members", "Aktive Klassenmitglieder"),
                            ("hidden", "Nicht sichtbar"),
                        ],
                        default="hidden",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Household",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                (
                    "members",
                    models.ManyToManyField(related_name="households", to="core.person"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuardianChildRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("mother", "Mutter"),
                            ("father", "Vater"),
                            ("guardian", "Sorgeberechtigte Person"),
                            ("foster", "Pflegeelternteil"),
                            ("step", "Stiefelternteil"),
                            ("other", "Sonstige autorisierte Bezugsperson"),
                        ],
                        max_length=24,
                    ),
                ),
                ("is_legal_guardian", models.BooleanField(default=False)),
                ("may_view_student_profile", models.BooleanField(default=False)),
                ("may_manage_profile", models.BooleanField(default=False)),
                ("may_manage_general_consents", models.BooleanField(default=False)),
                ("may_manage_photo_consents", models.BooleanField(default=False)),
                ("may_manage_biometric_consents", models.BooleanField(default=False)),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Unbestätigt"),
                            ("verified", "Bestätigt"),
                            ("revoked", "Widerrufen"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guardian_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_relationships",
                        to="core.person",
                    ),
                ),
                (
                    "student_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_relationships",
                        to="core.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsentDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("granted", "Zugestimmt"),
                            ("denied", "Abgelehnt"),
                            ("revoked", "Widerrufen"),
                        ],
                        max_length=16,
                    ),
                ),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(default="web", max_length=64)),
                (
                    "text_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.consenttextversion",
                    ),
                ),
                (
                    "consent_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.consenttype",
                    ),
                ),
                (
                    "deciding_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consent_decisions",
                        to="core.person",
                    ),
                ),
                (
                    "subject_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents_about",
                        to="core.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint_hash", models.CharField(max_length=64, unique=True)),
                ("endpoint", models.TextField()),
                ("p256dh", models.TextField()),
                ("auth", models.TextField()),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary_admin", "Hauptadministrator"),
                            ("deputy_admin", "Stellvertretender Administrator"),
                            ("teacher", "Klassenlehrer"),
                            ("editor", "Redakteur"),
                            ("moderator", "Moderator"),
                            ("organizer", "Organisator"),
                            ("guardian", "Elternteil"),
                            ("push_subscriber", "Benachrichtigungs-Abonnent"),
                        ],
                        max_length=32,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.schoolclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("ended", "Beendet"),
                            ("suspended", "Gesperrt"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.person"
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.schoolclass",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="schoolclass",
            name="school_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.schoolyear"
            ),
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_photo_reference",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.person"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="consenttextversion",
            constraint=models.UniqueConstraint(
                fields=("consent_type", "version"), name="unique_consent_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="guardianchildrelationship",
            constraint=models.UniqueConstraint(
                fields=("guardian_person", "student_person"),
                name="unique_guardian_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="guardianchildrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(("guardian_person", models.F("student_person")), _negated=True),
                name="guardian_not_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.UniqueConstraint(
                fields=("user", "school_class", "role"), name="unique_user_class_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="classmembership",
            constraint=models.UniqueConstraint(
                fields=("school_class", "person"), name="unique_class_person"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                fields=("name", "school_year"), name="unique_class_year"
            ),
        ),
    ]
