# Generated by Django 5.2.17 on 2026-08-24 21:48

from django.db import migrations

import klasse5e.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="useraccount",
            managers=[
                ("objects", klasse5e.core.models.UserAccountManager()),
            ],
        ),
    ]
