# Generated by Django 5.2.17 on 2026-09-01 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_class_codes(apps, schema_editor):
    SchoolClass = apps.get_model("core", "SchoolClass")
    for item in SchoolClass.objects.select_related("school").all():
        base = (item.name or f"class-{item.pk}").strip().lower().replace(" ", "-")[:50]
        candidate = base
        suffix = 1
        while SchoolClass.objects.filter(
            school=item.school, school_year=item.school_year, code=candidate
        ).exclude(pk=item.pk).exists():
            suffix += 1
            candidate = f"{base}-{suffix}"
        item.code = candidate
        item.save(update_fields=["code"])


def assign_existing_domain(apps, schema_editor):
    SchoolClass = apps.get_model("core", "SchoolClass")
    ClassDomain = apps.get_model("core", "ClassDomain")
    item = SchoolClass.objects.order_by("pk").first()
    if item:
        ClassDomain.objects.get_or_create(
            school_class=item,
            defaults={"hostname": "5e.klassid.de", "is_reserved_exception": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_school_branding_and_class_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('logo', 'Logo'), ('hero', 'Titelbild')], max_length=12)),
                ('image', models.ImageField(upload_to='branding/opaque/')),
                ('preview', models.ImageField(blank=True, upload_to='branding/opaque/')),
                ('alt_text', models.CharField(max_length=180)),
                ('rights_notice', models.CharField(blank=True, max_length=240)),
                ('publication_rights_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('removed', 'Entfernt')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=253, unique=True)),
                ('is_reserved_exception', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_text', models.CharField(max_length=160)),
                ('colors', models.CharField(blank=True, max_length=300)),
                ('motifs', models.CharField(blank=True, max_length=500)),
                ('style', models.CharField(blank=True, max_length=300)),
                ('reference_notes', models.CharField(blank=True, max_length=1000)),
                ('transparent_background', models.BooleanField(default=True)),
                ('intended_uses', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('submitted', 'Eingereicht'), ('review', 'In Prüfung'), ('question', 'Rückfrage'), ('offer', 'Angebot'), ('commissioned', 'Beauftragt'), ('delivered', 'Geliefert'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert')], default='draft', max_length=20)),
                ('admin_notes', models.CharField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortalConfigurationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('value_type', models.CharField(choices=[('boolean', 'Ja/Nein'), ('string', 'Text')], max_length=12)),
                ('default_value', models.JSONField()),
                ('school_override_allowed', models.BooleanField(default=False)),
                ('class_override_allowed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortalConfigurationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='schoolclass',
            name='unique_school_class_year',
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='address2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='school',
            name='director',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='fax',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='federal_state',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='legal_status',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='school',
            name='location_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='school',
            name='possible_duplicate_group',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='school',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='provider',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='school',
            name='search_name',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='source_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='source_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='school',
            name='source_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='grade_level',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='status',
            field=models.CharField(default='active', max_length=24),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(populate_class_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('primary_admin', 'Hauptadministrator'), ('school_admin', 'Schuladministrator'), ('class_admin', 'Klassenadministrator'), ('deputy_admin', 'Stellvertretender Administrator'), ('teacher', 'Klassenlehrer'), ('editor', 'Redakteur'), ('moderator', 'Moderator'), ('organizer', 'Organisator'), ('guardian', 'Elternteil'), ('push_subscriber', 'Benachrichtigungs-Abonnent')], max_length=32),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('school', 'code', 'school_year'), name='unique_school_class_year'),
        ),
        migrations.AddField(
            model_name='brandingasset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brandingasset',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branding_assets', to='core.school'),
        ),
        migrations.AddField(
            model_name='brandingasset',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branding_assets', to='core.schoolclass'),
        ),
        migrations.AddField(
            model_name='classdomain',
            name='school_class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='core.schoolclass'),
        ),
        migrations.RunPython(assign_existing_domain, migrations.RunPython.noop),
        migrations.AddField(
            model_name='logorequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logorequest',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='logorequest',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schoolclass'),
        ),
        migrations.AddField(
            model_name='portalconfigurationvalue',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.portalconfigurationkey'),
        ),
        migrations.AddField(
            model_name='portalconfigurationvalue',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='portalconfigurationvalue',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schoolclass'),
        ),
        migrations.AddField(
            model_name='portalconfigurationvalue',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='brandingasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('school__isnull', False), ('school_class__isnull', True)), models.Q(('school__isnull', True), ('school_class__isnull', False)), _connector='OR'), name='branding_exactly_one_scope'),
        ),
        migrations.AddConstraint(
            model_name='brandingasset',
            constraint=models.UniqueConstraint(condition=models.Q(('school__isnull', False), ('status', 'active')), fields=('school', 'kind'), name='one_active_school_branding_kind'),
        ),
        migrations.AddConstraint(
            model_name='brandingasset',
            constraint=models.UniqueConstraint(condition=models.Q(('school_class__isnull', False), ('status', 'active')), fields=('school_class', 'kind'), name='one_active_class_branding_kind'),
        ),
        migrations.AddConstraint(
            model_name='logorequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('school__isnull', False), ('school_class__isnull', True)), models.Q(('school__isnull', True), ('school_class__isnull', False)), _connector='OR'), name='logo_request_exactly_one_scope'),
        ),
        migrations.AddConstraint(
            model_name='portalconfigurationvalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('school__isnull', True), ('school_class__isnull', True)), models.Q(('school__isnull', False), ('school_class__isnull', True)), models.Q(('school__isnull', True), ('school_class__isnull', False)), _connector='OR'), name='configuration_at_most_one_scope'),
        ),
        migrations.AddConstraint(
            model_name='portalconfigurationvalue',
            constraint=models.UniqueConstraint(fields=('key', 'school', 'school_class'), name='unique_configuration_scope'),
        ),
    ]
