# Generated by Django 5.2.17 on 2026-09-01 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_modules(apps, schema_editor):
    PortalModule = apps.get_model("core", "PortalModule")
    modules = [
        ("pdf_forms", "PDF-Formulare", "beta", True, []),
        ("gallery", "Fotogalerie", "beta", True, []),
        ("photo_memory", "Photo Memory", "experimental", False, ["gallery"]),
        ("chat", "Chat", "beta", True, []),
        ("webuntis_timetable", "WebUntis-Stundenplan", "beta", True, []),
        ("webuntis_homework", "WebUntis-Hausaufgaben", "experimental", False, ["webuntis_timetable"]),
        ("itslearning", "itslearning", "experimental", False, []),
        ("contacts", "Kontakte", "beta", False, []),
        ("calendar", "Termine und Kalender", "beta", True, []),
        ("events", "Events und Mitbringlisten", "beta", True, []),
        ("push", "Push", "beta", True, []),
    ]
    for key, label, stability, enabled, dependencies in modules:
        PortalModule.objects.update_or_create(
            key=key,
            defaults={"label": label, "stability": stability, "default_enabled": enabled, "dependencies": dependencies},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_brandingasset_classdomain_logorequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('stability', models.CharField(choices=[('stable', 'Stabil'), ('beta', 'Beta'), ('experimental', 'Experimentell')], max_length=16)),
                ('default_enabled', models.BooleanField(default=False)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('last_successful_test_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortalModuleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField()),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.portalmodule')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.schoolclass')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('school__isnull', True), ('school_class__isnull', True)), models.Q(('school__isnull', False), ('school_class__isnull', True)), models.Q(('school__isnull', True), ('school_class__isnull', False)), _connector='OR'), name='module_override_at_most_one_scope'), models.UniqueConstraint(fields=('module', 'school', 'school_class'), name='unique_module_override_scope')],
            },
        ),
        migrations.RunPython(seed_modules, migrations.RunPython.noop),
    ]
