# Generated by Django 5.2.17 on 2026-09-01 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_portalmodule_portalmoduleoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='person',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profiles/opaque/'),
        ),
        migrations.AddField(
            model_name='person',
            name='street',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='device_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='RegistrationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('email_pending', 'E-Mail-Prüfung ausstehend'), ('review_pending', 'Wartet auf Prüfung'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt'), ('activated', 'Aktiviert')], default='email_pending', max_length=24)),
                ('email_token_hash', models.CharField(max_length=64, unique=True)),
                ('email_token_expires_at', models.DateTimeField()),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.CharField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.schoolclass')),
            ],
        ),
        migrations.CreateModel(
            name='ActivationGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.registrationapplication')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SlugField(max_length=40)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=128)),
                ('revision', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(blank=True, max_length=240)),
                ('target_url', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoolclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'school_class', 'read_at'], name='core_userno_user_id_d37cf3_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'school_class', 'object_type', 'object_id', 'revision'), name='unique_personal_notification_revision')],
            },
        ),
    ]
