# Generated by Django 5.2.17 on 2026-09-02 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_person_city_person_postal_code_person_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('idea', 'Idee'), ('note', 'Anmerkung'), ('bug', 'Fehler')], max_length=12)),
                ('page_path', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=3000)),
                ('screenshot', models.ImageField(blank=True, upload_to='pilot-reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.schoolclass')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
