# Generated by Django 5.2.17 on 2026-09-07 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_person_profile_image_mode_and_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar_seed',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='field_visibility',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ChildJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Wartet auf Prüfung'), ('approved', 'Bestätigt'), ('rejected', 'Abgelehnt')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.schoolclass')),
            ],
        ),
    ]
