# Generated by Django 5.2.17 on 2026-09-08 06:18

from django.db import migrations, models


def seed_idle_timeout(apps, schema_editor):
    Key = apps.get_model("core", "PortalConfigurationKey")
    Key.objects.update_or_create(
        key="session_idle_timeout_minutes",
        defaults={
            "version": 1,
            "value_type": "integer",
            "default_value": 15,
            "school_override_allowed": False,
            "class_override_allowed": False,
            "active": True,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_parent_representative_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portalconfigurationkey",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("boolean", "Ja/Nein"),
                    ("string", "Text"),
                    ("integer", "Ganze Zahl"),
                ],
                max_length=12,
            ),
        ),
        migrations.RunPython(seed_idle_timeout, migrations.RunPython.noop),
    ]
