# Generated by Django 5.2.17 on 2026-09-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_merge_role_branches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleassignment",
            name="role",
            field=models.CharField(
                choices=[
                    ("primary_admin", "Hauptadministrator"),
                    ("school_admin", "Schuladministrator"),
                    ("class_admin", "Klassenadministrator"),
                    ("deputy_admin", "Stellvertretender Administrator"),
                    ("teacher", "Klassenlehrer"),
                    ("editor", "Redakteur"),
                    ("moderator", "Moderator"),
                    ("organizer", "Organisator"),
                    ("guardian", "Elternteil"),
                    ("parent_representative", "Elternvertretung"),
                    ("push_subscriber", "Benachrichtigungs-Abonnent"),
                ],
                max_length=32,
            ),
        ),
    ]
