# Generated by Django 5.2.17 on 2026-09-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_use_root_portal_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email_visibility",
            field=models.CharField(
                choices=[
                    ("self", "Nur eigene Person"),
                    ("admins", "Administratoren"),
                    ("teachers", "Klassenlehrer und Administratoren"),
                    ("members", "Aktive Klassenmitglieder"),
                    ("hidden", "Nicht sichtbar"),
                ],
                default="hidden",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone_visibility",
            field=models.CharField(
                choices=[
                    ("self", "Nur eigene Person"),
                    ("admins", "Administratoren"),
                    ("teachers", "Klassenlehrer und Administratoren"),
                    ("members", "Aktive Klassenmitglieder"),
                    ("hidden", "Nicht sichtbar"),
                ],
                default="hidden",
                max_length=16,
            ),
        ),
    ]
