# Generated by Django 5.2.17 on 2026-09-11 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_private_contact_visibility_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component", models.CharField(max_length=48, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ok", "In Ordnung"),
                            ("warning", "Warnung"),
                            ("critical", "Kritisch"),
                        ],
                        default="ok",
                        max_length=16,
                    ),
                ),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_reported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["component"],
            },
        ),
        migrations.CreateModel(
            name="MonitoringSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(db_index=True, max_length=32)),
                (
                    "captured_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("values", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-captured_at", "-id"],
            },
        ),
    ]
