# Generated by Django 5.2.17 on 2026-09-12 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_monitoringcomponent_monitoringsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("female", "Weiblich"),
                    ("male", "Männlich"),
                    ("other", "Divers"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="familyaccesscode",
            name="existing_guardian_relationship_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("guardian", "Sorgeberechtigte Person"),
                    ("foster", "Pflegeelternteil"),
                    ("step", "Stiefelternteil"),
                    ("other", "Sonstige autorisierte Bezugsperson"),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="guardianchildrelationship",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("guardian", "Sorgeberechtigte Person"),
                    ("foster", "Pflegeelternteil"),
                    ("step", "Stiefelternteil"),
                    ("other", "Sonstige autorisierte Bezugsperson"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "route",
                    models.CharField(
                        help_text="z.B. /einstellungen/profil/", max_length=200
                    ),
                ),
                (
                    "icon",
                    models.CharField(help_text="Emoji wie 👤 oder ⚙️", max_length=10),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Sortierung im Menü"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
