# Generated by Django 5.2.17 on 2026-09-21 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_remove_portal_presentation_and_normalize_relationships"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleModulePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary_admin", "Hauptadministrator"),
                            ("school_admin", "Schuladministrator"),
                            ("class_admin", "Klassenadministrator"),
                            ("deputy_admin", "Stellvertretender Administrator"),
                            ("teacher", "Lehrer"),
                            ("school_leadership", "Schulleitung"),
                            ("content_manager", "Content Manager"),
                            ("editor", "Redakteur"),
                            ("moderator", "Moderator"),
                            ("organizer", "Organisator"),
                            ("guardian", "Elternteil"),
                            ("student", "Schüler"),
                            ("parent_representative", "Elternvertretung"),
                            (
                                "deputy_parent_representative",
                                "Stellvertretende Elternvertretung",
                            ),
                            ("push_subscriber", "Benachrichtigungs-Abonnent"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Sichtbar"),
                            ("read", "Lesen"),
                            ("create", "Erstellen"),
                            ("edit", "Bearbeiten"),
                            ("moderate", "Moderieren"),
                            ("publish", "Veröffentlichen"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("platform", "Plattform"),
                            ("school", "Schule"),
                            ("class", "Klasse"),
                            ("own", "Eigene Daten"),
                        ],
                        default="class",
                        max_length=16,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="core.portalmodule",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_role_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "module", "action"),
                        name="unique_role_module_action_permission",
                    )
                ],
            },
        ),
    ]
