# Generated by Django 5.2.17 on 2026-08-26 16:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_alter_useraccount_managers"),
        ("media", "0003_photo_biometric_analysis_allowed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "vision_collection_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("pipeline_id", models.CharField(max_length=80)),
                ("model_version", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("disabled", "Deaktiviert"),
                            ("deletion_pending", "Löschung ausstehend"),
                        ],
                        default="active",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "school_class",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.schoolclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BiometricProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "vision_subject_id",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("deletion_pending", "Löschung ausstehend"),
                            ("deleted", "Gelöscht"),
                        ],
                        default="active",
                        max_length=24,
                    ),
                ),
                ("consent_version", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deletion_requested_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biometrics.biometriccollection",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisionPhotoSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "vision_image_id",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("vision_job_id", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Vorgemerkt"),
                            ("analyzing", "Analyse"),
                            ("ready", "Bereit"),
                            ("failed", "Fehlgeschlagen"),
                            ("source_purged", "Quelldatei entfernt"),
                            ("deletion_pending", "Löschung ausstehend"),
                            ("deleted", "Gelöscht"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                ("pipeline_id", models.CharField(max_length=80)),
                ("model_version", models.CharField(blank=True, max_length=120)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("source_delete_due_at", models.DateTimeField()),
                ("source_deleted_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biometrics.biometriccollection",
                    ),
                ),
                (
                    "photo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="media.photo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BiometricMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("vision_face_id", models.CharField(max_length=128)),
                ("vision_match_id", models.CharField(max_length=128)),
                (
                    "score",
                    models.FloatField(help_text="Modellwert, keine Prozentwahrscheinlichkeit"),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Vorschlag"),
                            ("confirmed", "Bestätigt"),
                            ("rejected", "Verworfen"),
                            ("deleted", "Gelöscht"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("vision_actor_id", models.UUIDField(editable=False, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("add_as_reference", models.BooleanField(default=False)),
                ("pipeline_id", models.CharField(max_length=80)),
                ("model_version", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biometrics.biometriccollection",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biometrics.biometricprofile",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biometrics.visionphotosubmission",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="biometricprofile",
            constraint=models.UniqueConstraint(
                fields=("collection", "vision_subject_id"),
                name="unique_vision_subject_collection",
            ),
        ),
        migrations.AddConstraint(
            model_name="visionphotosubmission",
            constraint=models.UniqueConstraint(
                fields=("collection", "vision_image_id"),
                name="unique_vision_image_collection",
            ),
        ),
        migrations.AddConstraint(
            model_name="biometricmatch",
            constraint=models.UniqueConstraint(
                fields=("collection", "vision_match_id"),
                name="unique_vision_match_collection",
            ),
        ),
    ]
