# Generated by Django 5.2.17 on 2026-08-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biometrics", "0001_initial"),
        ("core", "0002_alter_useraccount_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="visionphotosubmission",
            name="manual_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="biometricprofile",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.studentprofile"
            ),
        ),
        migrations.AddConstraint(
            model_name="biometricprofile",
            constraint=models.UniqueConstraint(
                fields=("collection", "student"),
                name="unique_biometric_student_collection",
            ),
        ),
    ]
