# Generated by Django 5.2.17 on 2026-08-26 18:27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biometrics", "0003_biometricreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biometricreference",
            name="vision_reference_id",
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=128),
        ),
    ]
