# Generated by Django 5.2.17 on 2026-08-27 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuntis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('timezone_name', models.CharField(default='Europe/Berlin', max_length=64)),
                ('times', models.JSONField(default=list)),
                ('weekdays_only', models.BooleanField(default=True)),
                ('weekends', models.BooleanField(default=False)),
                ('holidays', models.BooleanField(default=False)),
                ('max_runs_per_day', models.PositiveSmallIntegerField(default=2)),
                ('min_interval_minutes', models.PositiveSmallIntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='webuntisconnection',
            name='status',
            field=models.CharField(choices=[('not_tested', 'Noch nicht geprüft'), ('ok', 'Verbindung eingerichtet'), ('invalid', 'Zugangsdaten ungültig'), ('mfa_required', 'MFA oder SSO erforderlich'), ('error', 'Verbindung fehlerhaft'), ('removed', 'Verbindung entfernt')], default='not_tested', max_length=24),
        ),
        migrations.AlterField(
            model_name='webuntisfeaturepreference',
            name='key',
            field=models.CharField(choices=[('timetable', 'Persönlicher Stundenplan'), ('timetable_extended', 'Erweiterte Stundeninformationen'), ('substitutions', 'Stundenplanänderungen und Vertretungen'), ('exams', 'Prüfungen'), ('homework', 'Hausaufgaben'), ('holidays', 'Ferien'), ('timegrid', 'Stundenraster'), ('subjects', 'Fächer'), ('rooms', 'Räume'), ('teachers', 'Lehrkräfte'), ('schoolyears', 'Schuljahre'), ('statusdata', 'Status- und Änderungshinweise'), ('class_reg_events', 'Klassenbucheinträge (nicht aktiviert)'), ('class_reg_categories', 'Klassenbuchkategorien (nicht aktiviert)'), ('class_reg_category_groups', 'Klassenbuch-Kategoriegruppen (nicht aktiviert)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='webuntisfeaturepreference',
            name='state',
            field=models.CharField(choices=[('available', 'Verfügbar'), ('not_authorized', 'Nicht berechtigt'), ('unsupported', 'Nicht durch diesen Adapter unterstützt'), ('not_checked', 'Noch nicht geprüft')], default='not_checked', max_length=24),
        ),
        migrations.AlterField(
            model_name='webuntishomework',
            name='visibility',
            field=models.CharField(choices=[('class', 'Klassenweit'), ('personal', 'Persönlich')], default='personal', max_length=12),
        ),
        migrations.AlterField(
            model_name='webuntislesson',
            name='visibility',
            field=models.CharField(choices=[('class', 'Klassenweit'), ('personal', 'Persönlich')], default='personal', max_length=12),
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('manual', 'Manuell'), ('automatic', 'Automatisch')], max_length=16)),
                ('status', models.CharField(choices=[('running', 'L�uft'), ('success', 'Erfolgreich'), ('no_change', 'Keine �nderungen'), ('failed', 'Fehlgeschlagen'), ('throttled', 'Zu h�ufig')], default='running', max_length=16)),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('change_count', models.PositiveIntegerField(default=0)),
                ('categories', models.JSONField(default=list)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='webuntis.webuntisconnection')),
            ],
        ),
    ]
