# Generated by Django 5.2.17 on 2026-09-01 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webuntis", "0002_syncschedule_alter_webuntisconnection_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebUntisSubjectMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="WebUntisTeacherMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="webuntisconnection",
            name="external_student_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webuntislesson",
            name="subject_code",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="webuntislesson",
            name="teacher_code",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name="WebUntisCalendarSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_subscriptions",
                        to="webuntis.webuntisconnection",
                    ),
                ),
            ],
        ),
    ]
