# Generated by Django 5.2.17 on 2026-09-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webuntis", "0003_webuntissubjectmapping_webuntisteachermapping_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncschedule",
            name="max_runs_per_day",
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
