# Generated by Django 5.2.17 on 2026-09-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuntis', '0005_configure_three_daily_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncrun',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='terminal_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncschedule',
            name='interval_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncschedule',
            name='last_duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncschedule',
            name='last_error_class',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='syncschedule',
            name='last_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncschedule',
            name='last_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncschedule',
            name='last_status',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='syncschedule',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncschedule',
            name='mode',
            field=models.CharField(choices=[('interval', 'Festes Intervall'), ('fixed_times', 'Feste Uhrzeiten')], default='fixed_times', max_length=16),
        ),
        migrations.AddField(
            model_name='syncschedule',
            name='next_run_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='syncschedule',
            name='source',
            field=models.CharField(default='webuntis', max_length=40, unique=True),
        ),
    ]
