# Generated by Django 5.2.17 on 2026-09-08 06:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def add_preferences(apps, schema_editor):
    Connection = apps.get_model("webuntis", "WebUntisConnection")
    Preference = apps.get_model("webuntis", "WebUntisFeaturePreference")
    for connection in Connection.objects.all():
        Preference.objects.get_or_create(
            connection=connection, key="absences", defaults={"enabled": False}
        )


def remove_preferences(apps, schema_editor):
    apps.get_model("webuntis", "WebUntisFeaturePreference").objects.filter(key="absences").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_parent_representative_role"),
        ("webuntis", "0008_homeworkprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_preferences, remove_preferences),
        migrations.AlterField(
            model_name="webuntisfeaturepreference",
            name="key",
            field=models.CharField(
                choices=[
                    ("timetable", "Persönlicher Stundenplan"),
                    ("timetable_extended", "Erweiterte Stundeninformationen"),
                    ("substitutions", "Stundenplanänderungen und Vertretungen"),
                    ("exams", "Prüfungen"),
                    ("homework", "Hausaufgaben"),
                    ("absences", "Abwesenheiten"),
                    ("holidays", "Ferien"),
                    ("timegrid", "Stundenraster"),
                    ("subjects", "Fächer"),
                    ("rooms", "Räume"),
                    ("teachers", "Lehrkräfte"),
                    ("schoolyears", "Schuljahre"),
                    ("statusdata", "Status- und Änderungshinweise"),
                    ("class_reg_events", "Klassenbucheinträge (nicht aktiviert)"),
                    ("class_reg_categories", "Klassenbuchkategorien (nicht aktiviert)"),
                    (
                        "class_reg_category_groups",
                        "Klassenbuch-Kategoriegruppen (nicht aktiviert)",
                    ),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="AbsenceDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "starts_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("ends_on", models.DateField(default=django.utils.timezone.localdate)),
                ("starts_time", models.TimeField(blank=True, null=True)),
                ("ends_time", models.TimeField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("sick", "Krank"),
                            ("doctor", "Arztbesuch"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.person"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebUntisAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=128)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("starts_time", models.TimeField(blank=True, null=True)),
                ("ends_time", models.TimeField(blank=True, null=True)),
                ("source_status", models.CharField(blank=True, max_length=80)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="webuntis.webuntisconnection",
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_on", "-pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("connection", "external_id"),
                        name="unique_webuntis_absence",
                    )
                ],
            },
        ),
    ]
