# Generated by Django 5.2.17 on 2026-09-01 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_person_city_person_postal_code_person_profile_photo_and_more'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('after_period', models.PositiveSmallIntegerField()),
                ('time_grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='schedule.timegrid')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('time_grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='schedule.timegrid')),
            ],
            options={
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('time_grid', 'number'), name='unique_grid_period')],
            },
        ),
    ]
